accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
   path('signup/', views.SignUpView.as_view(), name='signup'),
]

myapptdl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
   path('admin/', admin.site.urls),
   path('tdl/', include('tdl.urls')),
   path('accounts/', include('accounts.urls')),
   path('accounts/', include('django.contrib.auth.urls')),
   path('', RedirectView.as_view(url='/tdl/')),
]

tdl/urls.py
from django.urls import path
from . import views

app_name = 'tdl'

urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('execution/', views.ExecutionView.as_view(), name='execution'),
  path('create/', views.CreateView.as_view(), name='create'),
  path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
  path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

accounts/models.py
from django.db import models

# Create your models here.

tdl/models.py
from django.db import models
from django.urls import reverse

class Tdl(models.Model):
    item = models.CharField(max_length=200)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.item

    def get_absolute_url(self):
#       return reverse('tdl:index', kwargs={'pk': self.pk})
       return reverse('tdl:index')

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
   form_class = UserCreationForm
   success_url = reverse_lazy('login')
   template_name = 'accounts/signup.html'

tdl/views.py
from django.urls import reverse_lazy
from django.views import generic
from .models import Tdl
import random
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

class IndexView(generic.ListView):
   model = Tdl

   def get_queryset(self):
       id = self.request.user.id
       return Tdl.objects.filter(author_id=id)

class ExecutionView(LoginRequiredMixin, generic.ListView):
  model = Tdl
  template_name = 'tdl/tdl_execution.html'

  def get_queryset(self):
#    return Tdl.objects.order_by('?')[:1]
        id = self.request.user.id
        pk = Tdl.objects.filter(author_id=id).values_list('pk', flat=True)
        pk_list = list(pk)
        pk_random = random.choice(pk_list)
        queryset = Tdl.objects.filter(pk=pk_random)

        return queryset

class CreateView(LoginRequiredMixin, generic.edit.CreateView):
  model = Tdl
  fields = ['item'] #__all__'

  def form_valid(self, form):
      form.instance.author = self.request.user
      return super(CreateView, self).form_valid(form)

class UpdateView(LoginRequiredMixin, generic.edit.UpdateView):
  model = Tdl
  fields = ['item'] #__all__'

  def dispatch(self, request, *args, **kwargs):
      obj = self.get_object()
      if obj.author != self.request.user:
          raise PermissionError('編集権限がありません')
      return super(UpdateView, self).dispatch(request, *args, **kwargs)

class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):
  model = Tdl
  success_url = reverse_lazy('tdl:index')

  def dispatch(self, request, *args, **kwargs):
      obj = self.get_object()
      if obj.author != self.request.user:
          raise PermissionError('削除権限がありません')
      return super(Deletevies, self).dispatch(request, *args, **kwargs)

accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
<h1>Sign up</h1>
<section class='common-form'>
   <form method=post>
       {% csrf_token %}
       {{ form.as_p }}
       <button type='submit'>Sign up</button>
   </form>
</section>
{% endblock %}

tdl/templates/tdl/base.html
<!DOCTYPE html>
<html>
  <head>
      <meta charset="UTF-8">
      <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
      <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
      <style>body {padding-top:80px;}</style>
      <title>くじ引き</title>
  </head>
  <body>
      <nav class='navbar vabar-expand -sm navbar-dark bg-dark fixed-top'>
          <a class='navbar-brand' href='{% url "tdl:index" %}'>くじ引き</a>
      </nav>
      <div class='container'>
          {% block content %}
          {% endblock %}
      </div>
  </body>
</html>

tdl/templates/tdl/tdl_confirm_delete.html
{% extends './base.html' %}
{% block content %}

<h1>内容の削除</h1>

<p>'{{ object.item }}'を削除しますか？</p>

<form action ='' method='post'>{% csrf_token %}
   <button type='submit' class='submit delete'>削除する</button>
</form>

<div>
   <a href='JavaScript:history.back()'>戻る</a>
</div>

{% endblock %}

tdl/templates/tdl/tdl_execution.html
{% extends 'layout.html' %}
{% block content %}
     <h1>くじ引き結果</h1>

    <table class='table table-striped table-hover'>
        <tr>
            <th>内容</th>
        </tr>
        {% for tdl in object_list%}
        <tr>
            <td> {{ tdl.item }}</td>
        </tr>
        {% endfor %}
    </table>

    <div>
      <a href='JavaScript:history.back()'>戻る</a>
    </div>

{% endblock %}

tdl/templates/tdl/tdl_form.html
{% extends './base.html' %}
{% block content %}

<h1>くじ引きの情報{{ object|yesno:'更新,作成' }}</h1>

<form action ='' method='post'>{% csrf_token %}
  {{ form.as_p }}
  <button type='submit' class='submit'>{{ object|yesno:'更新,作成'}}</button>
</form>

<div>
  <a href='JavaScript:history.back()'>戻る</a>
</div>

{% endblock %}

tdl/templates/tdl/tdl_list.html
{% extends 'layout.html' %}
{% block content %}
    <h1>くじ引き内容</h1>

{% if user.is_authenticated %}
        <table class='table table-striped table-hover'>
            <tr>
                <th>内容</th><th>編集</th><th>削除</th>
            </tr>
            {% for tdl in object_list%}
            <tr>
                <td> {{ tdl.item }}</td>
                <td> <a href='{% url "tdl:update" tdl.id %}'>編集</a> </td>
                <td> <a href='{% url "tdl:delete" tdl.id %}'>削除</a> </td>
            </tr>
            {% endfor %}
        </table>
            <div>
                <a href='{% url "tdl:create" %}' class="btn btn-primary">新規作成</a>
                <a href='{% url "tdl:execution" %}' class="btn btn-secondary">実行</a>
            </div>
{% else %}
    <table class='table table-striped table-hover'>
        <tr>
            <th>内容</th>
        </tr>
        <tr>
            <td>サンプル1</td>
        </tr>
        <tr>
            <td>サンプル2</td>
        </tr>
    </table>
{% endif %}

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
  <head>
      <meta charset="UTF-8">
      <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
      <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
      <style>body {padding-top:80px;}</style>
      <title>くじ引き</title>
  </head>
  <body>
      <nav class='navbar navbar-expand -sm navbar-dark bg-dark fixed-top'>
          <a class='navbar-brand' href='{% url "tdl:index" %}'>くじ引き</a>
          <ul class='navbar-nav'>
               {% if user.is_authenticated %}
                   <li class='nav-item'>
                       <span class='navbar-text'>{{ user }} - </span>
                   </li>
                   <li class='nav-item'>
                       <a href='{% url "logout" %}' class='logout nav-link'>Logout</a>
               {% else %}
                    <li class='nav-item'>
                       <a href='{% url "login" %}' class='login nav-link'>Login</a>
                    </li>
                    <li class='nav-item'>
                       <a href='{% url "accounts:signup" %}' class='login nav-link'>Sign up</a>
                    </li>
               {% endif %}
      </nav>
      <div class='container'>
          {% block content %}
          {% endblock %}
      </div>
  </body>
</html>